### ISSUE TITLE
No 'PanToken' returned from authorised transaction.

### ISSUE THREAD

**Issue by csadler** [PowerTranz/PowerTranz-SDK-Win-Samples#3]
Having completed an authorised transaction the response "PanToken" is always _null_

Our solution would rely on the PanToken being returned in order to facilitate recurring payments or for CNP processing.

**Comment by reneemailhot** [comment]
This is a subscribed service.   Your account is enabled as to now pass the token back.

**Comment by csadler** [comment]
Thank you.  I can confirm we are receiving a token back now.
